"""
export_viz_samples.py
---------------------
Selects the N objects with the best and worst symmetry predictions for a given
experiment, copies their pipeline JSONs to results/, and generates a README
with the exact visualize_rays.py commands for each object.

"Good" = N objects with lowest angular error (status=="ok")
"Bad"  = N objects with highest angular error (status=="ok")
"No prediction" = objects with no valid prediction for this n_views (listed separately)

Output structure
----------------
<results_dir>/<experiment_id>/
├── viz_samples/
│   ├── good/
│   │   └── <object_id>/
│   │       ├── predicted_symmetry[_EXP].json
│   │       └── <size>/<lighting>/
│   │           ├── molmo_multiview[_EXP].json        ← from this experiment
│   │           ├── molmo_multiview[_BASE].json        ← copied from base exp (if --base-experiment-id)
│   │           ├── mapped_points_3d[_EXP].json
│   │           └── mapped_points_3d[_BASE].json       ← copied from base exp (if --base-experiment-id)
│   └── bad/
│       └── <object_id>/ (same structure)
├── objects_good.json     ← IDs + angular_error + n_points + sde
├── objects_bad.json
├── objects_no_pred.json  ← objects with no valid prediction
└── README.md             ← ready-to-run visualize_rays.py commands with comparison table

Usage
-----
python Mapping/export_viz_samples.py \\
    --renders-root ../data/renders \\
    --objects-root ../data/objects \\
    --symmetry-type axis_sym \\
    --experiment-id axis_v00 \\
    --method svd \\
    --results-dir ../results \\
    --sizes 224 --lightings flat \\
    --n-samples 10

# Cluster variant — pass base experiment to get comparison metrics and base JSONs copied:
python Mapping/export_viz_samples.py \\
    --renders-root ../data/renders \\
    --objects-root ../data/objects \\
    --symmetry-type axis_sym \\
    --experiment-id axis_v00_cluster \\
    --base-experiment-id axis_v00 \\
    --method svd \\
    --results-dir ../results \\
    --sizes 224 --lightings flat \\
    --n-samples 10
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
from datetime import date
from pathlib import Path

OBJECTS_SUBDIR = {
    "axis_sym":  "curated_axis_sym_obj",
    "plane_sym": "curated_plane_sym_obj",
}

METHODS = ["svd", "ransac_svd", "svd_sde", "ransac_svd_sde"]


# ── Helpers ───────────────────────────────────────────────────────────────────

def _exp_filename(base: str, experiment_id: str | None) -> str:
    if not experiment_id:
        return base
    dot = base.rfind(".")
    return f"{base[:dot]}_{experiment_id}{base[dot:]}"


def _results_json_path(renders_root: Path, symmetry_type: str,
                       sizes: list[int], lightings: list[str],
                       experiment_id: str | None, method: str) -> Path:
    size_tag  = "s" + "_".join(str(s) for s in sizes)
    light_tag = "_".join(lightings)
    exp_part  = f"_{experiment_id}" if experiment_id else ""
    return (renders_root / symmetry_type
            / f"eval_{size_tag}_{light_tag}{exp_part}_{method}_results.json")


def _select_samples(objects: dict, nv_key: str, n: int
                    ) -> tuple[list[dict], list[dict], list[dict]]:
    """Returns (good, bad, no_pred). good/bad sorted by angular_error_deg."""
    ok, no_pred = [], []
    for obj_id, obj_data in objects.items():
        if obj_data is None or nv_key not in obj_data:
            no_pred.append({"object_id": obj_id, "reason": "no_data"})
            continue
        m = obj_data[nv_key]
        if m.get("status") != "ok":
            no_pred.append({
                "object_id": obj_id,
                "reason":    m.get("status", "unknown"),
                "n_points":  m.get("n_points", 0),
            })
            continue
        ok.append({
            "object_id":         obj_id,
            "angular_error_deg": m.get("angular_error_deg"),
            "translation_error": m.get("translation_error"),
            "n_points":          m.get("n_points"),
            "n_inliers":         m.get("n_inliers"),
            "sde":               m.get("sde"),
            "accepted":          m.get("accepted"),
        })
    ok.sort(key=lambda x: x["angular_error_deg"])
    return ok[:n], ok[-n:][::-1], no_pred


def _copy_object_jsons(
    object_id:        str,
    renders_root:     Path,
    symmetry_type:    str,
    sizes:            list[int],
    lightings:        list[str],
    experiment_id:    str | None,
    dest_dir:         Path,
    base_exp_id:      str | None = None,
) -> None:
    """Copy pipeline JSONs for one object to dest_dir, preserving subdirectory structure.

    When base_exp_id is provided, also copies molmo_multiview and mapped_points_3d
    from the base experiment (those files are not re-generated by cluster variants).
    """
    dest_dir.mkdir(parents=True, exist_ok=True)
    obj_dir = renders_root / symmetry_type / object_id

    # Object-level JSON: predicted_symmetry[_EXP].json
    for base in ["predicted_symmetry.json"]:
        src = obj_dir / _exp_filename(base, experiment_id)
        if src.exists():
            shutil.copy2(src, dest_dir / src.name)

    # Size/lighting-level JSONs
    for size in sizes:
        for lighting in lightings:
            size_light_src = obj_dir / str(size) / lighting
            size_light_dst = dest_dir / str(size) / lighting
            size_light_dst.mkdir(parents=True, exist_ok=True)
            for base in ["molmo_multiview.json", "mapped_points_3d.json"]:
                # Copy this experiment's version (may not exist for cluster variants)
                src = size_light_src / _exp_filename(base, experiment_id)
                if src.exists():
                    shutil.copy2(src, size_light_dst / src.name)
                # Copy base experiment's version when provided
                if base_exp_id and base_exp_id != experiment_id:
                    base_src = size_light_src / _exp_filename(base, base_exp_id)
                    if base_src.exists():
                        shutil.copy2(base_src, size_light_dst / base_src.name)


def _load_base_metrics(
    renders_root:  Path,
    symmetry_type: str,
    sizes:         list[int],
    lightings:     list[str],
    base_exp_id:   str,
    method:        str,
    nv_key:        str,
    object_ids:    list[str],
) -> dict[str, dict]:
    """Load angular_error and n_points from the base experiment for comparison."""
    base_json = _results_json_path(renders_root, symmetry_type, sizes, lightings,
                                   base_exp_id, method)
    if not base_json.exists():
        print(f"[warn] Base experiment results not found: {base_json} — skipping comparison")
        return {}
    with open(base_json, encoding="utf-8") as f:
        data = json.load(f)
    objects = data.get("objects", {})
    result = {}
    for oid in object_ids:
        obj_data = objects.get(oid)
        if obj_data and nv_key in obj_data:
            m = obj_data[nv_key]
            if m.get("status") == "ok":
                result[oid] = {
                    "angular_error_deg": m.get("angular_error_deg"),
                    "n_points":          m.get("n_points"),
                    "sde":               m.get("sde"),
                }
    return result


def _generate_readme(
    out_path:       Path,
    good_objects:   list[dict],
    bad_objects:    list[dict],
    no_pred_count:  int,
    nv_key:         str,
    args:           argparse.Namespace,
    out_root:       Path,
    base_metrics:   dict[str, dict] | None = None,
) -> None:
    exp_id       = args.experiment_id or "(none)"
    base_exp_id  = getattr(args, "base_experiment_id", None)
    method       = args.method
    sym_type     = args.symmetry_type
    size         = args.sizes[0]
    lighting     = args.lightings[0]
    results_root = Path(args.results_dir)
    exp_folder   = args.experiment_id or f"{sym_type}_default"

    def _renders_root_for(exp: str | None, category: str) -> str:
        folder = exp if exp else f"{sym_type}_default"
        p = results_root / folder / "viz_samples" / category
        return "../" + p.as_posix()

    def _cmd(obj_id: str, extra_flags: str = "", category: str = "good",
             exp: str | None = None) -> list[str]:
        exp = exp or args.experiment_id
        lines = [
            "```bash",
            f"python Mapping/visualize_rays.py \\",
            f"    --object-id {obj_id} \\",
            f"    --renders-root {_renders_root_for(exp, category)} \\",
            f"    --objects-root {args.objects_root} \\",
            f"    --symmetry-type {sym_type} \\",
            f"    --size {size} --lighting {lighting} \\",
            f"    --n-views {nv_key}",
        ]
        if exp:
            lines[-1] += " \\"
            lines.append(f"    --experiment-id {exp}")
        if extra_flags:
            lines[-1] += " \\"
            lines.append(f"    {extra_flags}")
        lines.append("```")
        return lines

    all_flags = f"--show-gt --show-predicted --pred-method {method} --show-clusters"

    blocks = [
        f"# Viz samples — {exp_id}",
        f"",
        f"| Campo             | Valor |",
        f"|---|---|",
        f"| Experimento       | `{exp_id}` |",
    ]
    if base_exp_id:
        blocks.append(f"| Experimento base  | `{base_exp_id}` |")
    blocks += [
        f"| Tipo de simetría  | `{sym_type}` |",
        f"| Método de ranking | `{method}` |",
        f"| n\\_views           | {nv_key} |",
        f"| Objetos buenos    | {len(good_objects)} |",
        f"| Objetos malos     | {len(bad_objects)} |",
        f"| Sin predicción    | {no_pred_count} |",
        f"| Fecha             | {date.today()} |",
        f"",
        f"## Flags de visualización disponibles",
        f"",
        f"| Flag | Efecto |",
        f"|---|---|",
        f"| `--show-gt` | Muestra eje/plano GT (azul/verde) |",
        f"| `--show-predicted` | Muestra eje/plano predicho (rojo/magenta) |",
        f"| `--pred-method svd\\|ransac_svd\\|svd_sde\\|ransac_svd_sde` | Método a visualizar |",
        f"| `--show-clusters` | Muestra centroides de clusters (naranja-rojo) vs hits crudos (amarillo) |",
        f"| `--point-mode independent\\|midpoint` | Modo de colección de puntos (debe coincidir con estimate_symmetry.py) |",
        f"",
        f"---",
        f"",
        f"## Objetos con buena predicción (menor error angular)",
        f"",
    ]

    def _obj_block(obj: dict, category: str) -> list[str]:
        oid  = obj["object_id"]
        err  = obj["angular_error_deg"]
        npt  = obj["n_points"]
        sde  = obj.get("sde")
        sde_s = f"  |  SDE={sde:.4f}" if sde is not None else ""

        lines = [f"### `{oid}`", f""]

        if base_metrics and oid in base_metrics:
            bm      = base_metrics[oid]
            b_err   = bm["angular_error_deg"]
            b_npt   = bm["n_points"]
            b_sde   = bm.get("sde")
            delta   = err - b_err
            delta_s = f"+{delta:.2f}" if delta >= 0 else f"{delta:.2f}"
            b_sde_s = f"  |  SDE={b_sde:.4f}" if b_sde is not None else ""
            lines += [
                f"| Métrica           | `{base_exp_id}` (base) | `{exp_id}` (cluster) | Δ |",
                f"|---|---|---|---|",
                f"| angular\\_error    | {b_err:.2f}° | **{err:.2f}°** | {delta_s}° |",
                f"| n\\_points         | {b_npt} | {npt} | {npt - b_npt:+d} |",
            ]
            if sde is not None or b_sde is not None:
                b_sde_disp = f"{b_sde:.4f}" if b_sde is not None else "—"
                sde_disp   = f"{sde:.4f}"   if sde   is not None else "—"
                lines.append(f"| SDE               | {b_sde_disp} | {sde_disp} | — |")
            lines += [
                f"",
                f"**Sin cluster** (`{base_exp_id}`):",
                f"",
            ] + _cmd(oid, all_flags, category=category, exp=base_exp_id) + [
                f"",
                f"**Con cluster** (`{exp_id}`):",
                f"",
            ] + _cmd(oid, all_flags, category=category, exp=exp_id) + [""]
        else:
            lines += [
                f"> angular\\_error = **{err:.2f}°**  |  n\\_points = {npt}{sde_s}",
                f"",
            ] + _cmd(oid, all_flags, category=category) + [""]

        return lines

    for obj in good_objects:
        blocks += _obj_block(obj, category="good")

    blocks += [
        f"---",
        f"",
        f"## Objetos con mala predicción (mayor error angular)",
        f"",
    ]

    for obj in bad_objects:
        blocks += _obj_block(obj, category="bad")

    out_path.write_text("\n".join(blocks), encoding="utf-8")


# ── CLI ───────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Export visualization samples (good/bad predictions) for an experiment.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--renders-root",       required=True)
    p.add_argument("--objects-root",       required=True)
    p.add_argument("--symmetry-type",      required=True, choices=["axis_sym", "plane_sym"])
    p.add_argument("--results-dir",        required=True,
                   help="Root results folder. Output goes to <results_dir>/<experiment_id>/")
    p.add_argument("--method",             default="svd", choices=METHODS,
                   help="Fitting method used to rank good/bad objects.")
    p.add_argument("--experiment-id",      default=None)
    p.add_argument("--base-experiment-id", default=None,
                   help="Base experiment to compare against (e.g. axis_v00 when running axis_v00_cluster). "
                        "Copies base molmo_multiview/mapped_points JSONs and adds comparison table to README.")
    p.add_argument("--sizes",     type=int, nargs="+", default=[224])
    p.add_argument("--lightings", type=str, nargs="+", default=["flat"],
                   choices=["flat", "darker", "brighter"])
    p.add_argument("--n-views",   type=int, default=None,
                   help="n_views group for ranking. Default: maximum available.")
    p.add_argument("--n-samples", type=int, default=10,
                   help="Number of good + bad objects to export.")
    return p.parse_args()


def main() -> None:
    args      = parse_args()
    root      = Path(args.renders_root)
    sym_type  = args.symmetry_type
    exp_id    = args.experiment_id
    base_exp  = args.base_experiment_id
    folder    = exp_id if exp_id else f"{sym_type}_default"

    # ── Locate eval results JSON ───────────────────────────────────────────────
    results_json = _results_json_path(
        root, sym_type, args.sizes, args.lightings, exp_id, args.method
    )
    if not results_json.exists():
        raise SystemExit(f"[error] Results JSON not found: {results_json}\n"
                         f"        Run evaluate.py first.")

    with open(results_json, encoding="utf-8") as f:
        eval_data = json.load(f)

    objects = eval_data.get("objects", {})

    # ── Choose n_views ─────────────────────────────────────────────────────────
    all_nv: set[str] = set()
    for od in objects.values():
        if od:
            all_nv.update(od.keys())
    if not all_nv:
        raise SystemExit("[error] No n_views keys found in results JSON.")

    nv_key = str(args.n_views) if args.n_views else str(max(int(k) for k in all_nv))
    print(f"Using n_views = {nv_key}  (pass --n-views to override)")

    # ── Select samples ─────────────────────────────────────────────────────────
    good, bad, no_pred = _select_samples(objects, nv_key, args.n_samples)
    print(f"Good objects : {len(good)}")
    print(f"Bad objects  : {len(bad)}")
    print(f"No prediction: {len(no_pred)}")

    # ── Output directory ───────────────────────────────────────────────────────
    out_root = Path(args.results_dir) / folder
    out_root.mkdir(parents=True, exist_ok=True)

    # ── Copy JSONs ─────────────────────────────────────────────────────────────
    for category, sample_list in [("good", good), ("bad", bad)]:
        for obj in sample_list:
            oid      = obj["object_id"]
            dest_dir = out_root / "viz_samples" / category / oid
            _copy_object_jsons(
                oid, root, sym_type,
                args.sizes, args.lightings, exp_id, dest_dir,
                base_exp_id=base_exp,
            )
    print(f"JSONs copied → {out_root / 'viz_samples'}")

    # Create a symlink/junction <category>/<sym_type> -> <category>/ so that
    # visualize_rays.py (which appends symmetry_type to renders-root) resolves
    # <viz_root>/<sym_type>/<object_id>/... correctly without needing data/renders.
    for category in ("good", "bad"):
        cat_dir = out_root / "viz_samples" / category
        link = cat_dir / sym_type
        if not link.exists():
            try:
                os.symlink(str(cat_dir), str(link), target_is_directory=True)
            except (OSError, NotImplementedError):
                pass  # junction creation may require elevation on some Windows configs

    # ── Save object lists ──────────────────────────────────────────────────────
    (out_root / "objects_good.json").write_text(
        json.dumps(good,    indent=2, ensure_ascii=False), encoding="utf-8"
    )
    (out_root / "objects_bad.json").write_text(
        json.dumps(bad,     indent=2, ensure_ascii=False), encoding="utf-8"
    )
    (out_root / "objects_no_pred.json").write_text(
        json.dumps(no_pred, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    # ── Load base metrics for comparison (if --base-experiment-id given) ───────
    base_metrics: dict[str, dict] | None = None
    if base_exp:
        all_ids = [o["object_id"] for o in good + bad]
        base_metrics = _load_base_metrics(
            root, sym_type, args.sizes, args.lightings,
            base_exp, args.method, nv_key, all_ids,
        )
        print(f"Base metrics loaded for {len(base_metrics)} objects  ({base_exp})")

    # ── Generate README ────────────────────────────────────────────────────────
    readme_path = out_root / "README.md"
    _generate_readme(readme_path, good, bad, len(no_pred), nv_key, args, out_root,
                     base_metrics=base_metrics)
    print(f"README       → {readme_path}")
    print(f"\nDone. Results in: {out_root}")


if __name__ == "__main__":
    main()
